"""added a title to pitches Migration

Revision ID: 6a30494ce3c8
Revises: 7ce17d0e5066
Create Date: 2022-03-06 16:32:19.229875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a30494ce3c8'
down_revision = '7ce17d0e5066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
