"""update naming

Revision ID: 70be79cf09ae
Revises: 6a30494ce3c8
Create Date: 2022-03-06 18:31:27.504825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70be79cf09ae'
down_revision = '6a30494ce3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('dislike')
    op.drop_column('pitches', 'pitch_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('dislike',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='dislike_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='dislike_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dislike_pkey')
    )
    op.drop_table('dislikes')
    # ### end Alembic commands ###
